OBJECTS=
CFLAGS=-g -Wall -O1 -pedantic -std=c11
LDLIBS=
CC=cc

all: string_unique string_permutation

string_unique: $(OBJECTS)
string_permutation: $(OBJECTS)

clean:
	rm string_unique string_permutation
